version: '3.5'
services:
  influx:
    image: influxdb:1.0
    ports:
      - 8083:8083
      - 8086:8086
      - 7101:7101
      - 25826:25826/udp

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000