spring:
  application:
    name: service
  datasource:
    url: "jdbc:h2:mem:"
    driver-class-name: "org.h2.Driver"
  jpa:
    database: "h2"
    hibernate:
      ddl-auto: "create-drop"

management:
  metrics:
    export:
      influx:
        db: dominigeiger
        uri: http://localhost:8086
        enabled: true